### ISSUE TITLE
Keypair.fromSecretKey has a error "const encoder = new TextEncoder();"

### ISSUE THREAD

**Issue by 256yangwei** [yihau/solana-web3-demo#9]
```
// import { Connection, Keypair, LAMPORTS_PER_SOL } from "@solana/web3.js";
const { Connection, Keypair, LAMPORTS_PER_SOL } = require("@solana/web3.js");
// import * as bs58 from "bs58";
const bs58 = require("bs58");
 
// connection
// const connection = new Connection("https://api.mainnet-beta.solana.com");
const connection = new Connection("https://api.devnet.solana.com");

// 5YNmS1R9nNSCDzb5a7mMJ1dwK9uHeAAF4CmPEwKgVWr8
const feePayer = Keypair.fromSecretKey(
  bs58.decode("588FU4PktJWfGfxtzpAAXywSNt74AvtroVzGfKkVN1LwRuvHwKGr851uH8czM5qm4iqLbs1kKoMKtMJG4ATR7Ld2")
);

(async () => {
  let balance = await connection.getBalance(feePayer.publicKey);
  console.log(`${balance / LAMPORTS_PER_SOL} SOL`);
})();
```

**when I run the code ，Keypair.fromSecretKey has a problem , the response is blow：**
node .\query.js
E:\projects\nodejs\coins\src\node_modules\@solana\web3.js\lib\index.cjs.js:7320
      const encoder = new TextEncoder();
                      ^

ReferenceError: TextEncoder is not defined
    at Function.fromSecretKey (E:\projects\nodejs\coins\src\node_modules\@solana\web3.js\lib\index.cjs.js:7320:23)        
    at Object.<anonymous> (E:\projects\nodejs\coins\src\sol\query.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Anybody know how to solve it ?

**Comment by yihau** [comment]
I run the example with ts-node and work fine.
maybe you can upgrade your node js version first then install ts-node to run the example

**Comment by 256yangwei** [comment]
which version of nodejs do you use? you look like chinese? Is it OK to add a wechat friend?

**Comment by 256yangwei** [comment]
I have solve it ， the version of nodejs is low . I update it to v16.13.0，it work fine.

**Comment by yihau** [comment]
🎉
